
package br.gov.planejamento.sof.siop.servicoweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSExecucaoEstataisService", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", wsdlLocation = "file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSExecucaoEstatais.wsdl")
public class WSExecucaoEstataisService
    extends Service
{

    private final static URL WSEXECUCAOESTATAISSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSEXECUCAOESTATAISSERVICE_EXCEPTION;
    private final static QName WSEXECUCAOESTATAISSERVICE_QNAME = new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSExecucaoEstataisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSExecucaoEstatais.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSEXECUCAOESTATAISSERVICE_WSDL_LOCATION = url;
        WSEXECUCAOESTATAISSERVICE_EXCEPTION = e;
    }

    public WSExecucaoEstataisService() {
        super(__getWsdlLocation(), WSEXECUCAOESTATAISSERVICE_QNAME);
    }

    public WSExecucaoEstataisService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSEXECUCAOESTATAISSERVICE_QNAME, features);
    }

    public WSExecucaoEstataisService(URL wsdlLocation) {
        super(wsdlLocation, WSEXECUCAOESTATAISSERVICE_QNAME);
    }

    public WSExecucaoEstataisService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSEXECUCAOESTATAISSERVICE_QNAME, features);
    }

    public WSExecucaoEstataisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSExecucaoEstataisService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSExecucaoEstatais
     */
    @WebEndpoint(name = "WSExecucaoEstataisPort")
    public WSExecucaoEstatais getWSExecucaoEstataisPort() {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSExecucaoEstataisPort"), WSExecucaoEstatais.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSExecucaoEstatais
     */
    @WebEndpoint(name = "WSExecucaoEstataisPort")
    public WSExecucaoEstatais getWSExecucaoEstataisPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSExecucaoEstataisPort"), WSExecucaoEstatais.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSEXECUCAOESTATAISSERVICE_EXCEPTION!= null) {
            throw WSEXECUCAOESTATAISSERVICE_EXCEPTION;
        }
        return WSEXECUCAOESTATAISSERVICE_WSDL_LOCATION;
    }

}
