
package br.gov.planejamento.sof.siop.servicoweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSQualitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSQualitativo {


    /**
     * 
     * @param identificadorUnico
     * @param credencial
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterAcaoPorIdentificadorUnico", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcaoPorIdentificadorUnico")
    @ResponseWrapper(localName = "obterAcaoPorIdentificadorUnicoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcaoPorIdentificadorUnicoResponse")
    public RetornoAcoesDTO obterAcaoPorIdentificadorUnico(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "identificadorUnico", targetNamespace = "")
        Integer identificadorUnico);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoIniciativa
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterAcoesPorIniciativa", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorIniciativa")
    @ResponseWrapper(localName = "obterAcoesPorIniciativaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorIniciativaResponse")
    public RetornoAcoesDTO obterAcoesPorIniciativa(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoIniciativa", targetNamespace = "")
        String codigoIniciativa,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoOrgao
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoUo
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterAcoesPorOrgao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorOrgao")
    @ResponseWrapper(localName = "obterAcoesPorOrgaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorOrgaoResponse")
    public RetornoAcoesDTO obterAcoesPorOrgao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoOrgao", targetNamespace = "")
        String codigoOrgao,
        @WebParam(name = "codigoUo", targetNamespace = "")
        String codigoUo,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterAcoesPorPrograma", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorPrograma")
    @ResponseWrapper(localName = "obterAcoesPorProgramaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesPorProgramaResponse")
    public RetornoAcoesDTO obterAcoesPorPrograma(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param codigoIniciativa
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoFinanciamentoExtraOrcamentarioDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterFinanciamentoExtraOrcamentarioPorIniciativa", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterFinanciamentoExtraOrcamentarioPorIniciativa")
    @ResponseWrapper(localName = "obterFinanciamentoExtraOrcamentarioPorIniciativaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterFinanciamentoExtraOrcamentarioPorIniciativaResponse")
    public RetornoFinanciamentoExtraOrcamentarioDTO obterFinanciamentoExtraOrcamentarioPorIniciativa(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoIniciativa", targetNamespace = "")
        String codigoIniciativa,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento);

    /**
     * 
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoIndicadoresDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterIndicadoresPorPrograma", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterIndicadoresPorPrograma")
    @ResponseWrapper(localName = "obterIndicadoresPorProgramaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterIndicadoresPorProgramaResponse")
    public RetornoIndicadoresDTO obterIndicadoresPorPrograma(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoIniciativasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterIniciativasPorObjetivo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterIniciativasPorObjetivo")
    @ResponseWrapper(localName = "obterIniciativasPorObjetivoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterIniciativasPorObjetivoResponse")
    public RetornoIniciativasDTO obterIniciativasPorObjetivo(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param identificadorUnicoAcao
     * @param credencial
     * @param dataHoraReferencia
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoLocalizadoresDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLocalizadoresPorAcao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterLocalizadoresPorAcao")
    @ResponseWrapper(localName = "obterLocalizadoresPorAcaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterLocalizadoresPorAcaoResponse")
    public RetornoLocalizadoresDTO obterLocalizadoresPorAcao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "identificadorUnicoAcao", targetNamespace = "")
        Integer identificadorUnicoAcao,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param codigoIniciativa
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoMedidaInstitucionalNormativaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMedidaInstitucionalPorIniciativa", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMedidaInstitucionalPorIniciativa")
    @ResponseWrapper(localName = "obterMedidaInstitucionalPorIniciativaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMedidaInstitucionalPorIniciativaResponse")
    public RetornoMedidaInstitucionalNormativaDTO obterMedidaInstitucionalPorIniciativa(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoIniciativa", targetNamespace = "")
        String codigoIniciativa,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoMetasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMetasPorObjetivo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMetasPorObjetivo")
    @ResponseWrapper(localName = "obterMetasPorObjetivoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMetasPorObjetivoResponse")
    public RetornoMetasDTO obterMetasPorObjetivo(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param credencial
     * @param exercicio
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoMomentoDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMomentoCarga", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMomentoCarga")
    @ResponseWrapper(localName = "obterMomentoCargaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterMomentoCargaResponse")
    public RetornoMomentoDTO obterMomentoCarga(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio);

    /**
     * 
     * @param credencial
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoObjetivosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterObjetivosPorPrograma", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterObjetivosPorPrograma")
    @ResponseWrapper(localName = "obterObjetivosPorProgramaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterObjetivosPorProgramaResponse")
    public RetornoObjetivosDTO obterObjetivosPorPrograma(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoOrgao
     * @param credencial
     * @param dataHoraReferencia
     * @param exercicio
     * @param tipoOrgao
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoOrgaosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterOrgao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterOrgao")
    @ResponseWrapper(localName = "obterOrgaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterOrgaoResponse")
    public RetornoOrgaosDTO obterOrgao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoOrgao", targetNamespace = "")
        String codigoOrgao,
        @WebParam(name = "tipoOrgao", targetNamespace = "")
        String tipoOrgao,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param credencial
     * @param codigoSiorg
     * @param exercicio
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoOrgaosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterOrgaoPorCodigoSiorg", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterOrgaoPorCodigoSiorg")
    @ResponseWrapper(localName = "obterOrgaoPorCodigoSiorgResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterOrgaoPorCodigoSiorgResponse")
    public RetornoOrgaosDTO obterOrgaoPorCodigoSiorg(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoSiorg", targetNamespace = "")
        String codigoSiorg);

    /**
     * 
     * @param identificadorUnicoAcao
     * @param credencial
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoPlanoOrcamentarioDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPlanosOrcamentariosPorAcao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterPlanosOrcamentariosPorAcao")
    @ResponseWrapper(localName = "obterPlanosOrcamentariosPorAcaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterPlanosOrcamentariosPorAcaoResponse")
    public RetornoPlanoOrcamentarioDTO obterPlanosOrcamentariosPorAcao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "identificadorUnicoAcao", targetNamespace = "")
        Integer identificadorUnicoAcao);

    /**
     * 
     * @param retornarMetas
     * @param retornarRegionalizacoes
     * @param retornarAcoes
     * @param retornarOrgaos
     * @param exercicio
     * @param retornarLocalizadores
     * @param credencial
     * @param dataHoraReferencia
     * @param retornarMedidasInstitucionaisNormativas
     * @param retornarObjetivos
     * @param retornarIndicadores
     * @param retornarAgendaSam
     * @param codigoMomento
     * @param retornarIniciativas
     * @param retornarPlanosOrcamentarios
     * @param retornarProgramas
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoProgramacaoQualitativoDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterProgramacaoCompleta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramacaoCompleta")
    @ResponseWrapper(localName = "obterProgramacaoCompletaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramacaoCompletaResponse")
    public RetornoProgramacaoQualitativoDTO obterProgramacaoCompleta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "retornarOrgaos", targetNamespace = "")
        boolean retornarOrgaos,
        @WebParam(name = "retornarProgramas", targetNamespace = "")
        boolean retornarProgramas,
        @WebParam(name = "retornarIndicadores", targetNamespace = "")
        boolean retornarIndicadores,
        @WebParam(name = "retornarObjetivos", targetNamespace = "")
        boolean retornarObjetivos,
        @WebParam(name = "retornarIniciativas", targetNamespace = "")
        boolean retornarIniciativas,
        @WebParam(name = "retornarAcoes", targetNamespace = "")
        boolean retornarAcoes,
        @WebParam(name = "retornarLocalizadores", targetNamespace = "")
        boolean retornarLocalizadores,
        @WebParam(name = "retornarMetas", targetNamespace = "")
        boolean retornarMetas,
        @WebParam(name = "retornarRegionalizacoes", targetNamespace = "")
        boolean retornarRegionalizacoes,
        @WebParam(name = "retornarPlanosOrcamentarios", targetNamespace = "")
        boolean retornarPlanosOrcamentarios,
        @WebParam(name = "retornarAgendaSam", targetNamespace = "")
        boolean retornarAgendaSam,
        @WebParam(name = "retornarMedidasInstitucionaisNormativas", targetNamespace = "")
        boolean retornarMedidasInstitucionaisNormativas,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoOrgao
     * @param credencial
     * @param dataHoraReferencia
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoProgramasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterProgramasPorOrgao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramasPorOrgao")
    @ResponseWrapper(localName = "obterProgramasPorOrgaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramasPorOrgaoResponse")
    public RetornoProgramasDTO obterProgramasPorOrgao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoOrgao", targetNamespace = "")
        String codigoOrgao,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoObjetivo
     * @param credencial
     * @param codigoMeta
     * @param dataHoraReferencia
     * @param codigoPrograma
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoRegionalizacoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterRegionalizacoesPorMeta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterRegionalizacoesPorMeta")
    @ResponseWrapper(localName = "obterRegionalizacoesPorMetaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterRegionalizacoesPorMetaResponse")
    public RetornoRegionalizacoesDTO obterRegionalizacoesPorMeta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        String codigoPrograma,
        @WebParam(name = "codigoObjetivo", targetNamespace = "")
        String codigoObjetivo,
        @WebParam(name = "codigoMeta", targetNamespace = "")
        String codigoMeta,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param retornarBasesGeograficas
     * @param retornarUnidadesMedidaIndicador
     * @param retornarSubFuncoes
     * @param retornarPeriodicidades
     * @param retornarRegioes
     * @param retornarMomentos
     * @param exercicio
     * @param retornarTiposAcao
     * @param retonarFuncoes
     * @param retornarEsferas
     * @param retornarTiposPrograma
     * @param credencial
     * @param retornarPerfis
     * @param dataHoraReferencia
     * @param retornarUnidadesMedida
     * @param retornarProdutos
     * @param retornarTiposInclusao
     * @param retornarMacroDesafios
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoApoioQualitativoDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterTabelasApoio", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterTabelasApoio")
    @ResponseWrapper(localName = "obterTabelasApoioResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterTabelasApoioResponse")
    public RetornoApoioQualitativoDTO obterTabelasApoio(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "retornarMomentos", targetNamespace = "")
        boolean retornarMomentos,
        @WebParam(name = "retornarEsferas", targetNamespace = "")
        boolean retornarEsferas,
        @WebParam(name = "retornarTiposInclusao", targetNamespace = "")
        boolean retornarTiposInclusao,
        @WebParam(name = "retonarFuncoes", targetNamespace = "")
        boolean retonarFuncoes,
        @WebParam(name = "retornarSubFuncoes", targetNamespace = "")
        boolean retornarSubFuncoes,
        @WebParam(name = "retornarTiposAcao", targetNamespace = "")
        boolean retornarTiposAcao,
        @WebParam(name = "retornarProdutos", targetNamespace = "")
        boolean retornarProdutos,
        @WebParam(name = "retornarUnidadesMedida", targetNamespace = "")
        boolean retornarUnidadesMedida,
        @WebParam(name = "retornarRegioes", targetNamespace = "")
        boolean retornarRegioes,
        @WebParam(name = "retornarPerfis", targetNamespace = "")
        boolean retornarPerfis,
        @WebParam(name = "retornarTiposPrograma", targetNamespace = "")
        boolean retornarTiposPrograma,
        @WebParam(name = "retornarMacroDesafios", targetNamespace = "")
        boolean retornarMacroDesafios,
        @WebParam(name = "retornarUnidadesMedidaIndicador", targetNamespace = "")
        boolean retornarUnidadesMedidaIndicador,
        @WebParam(name = "retornarPeriodicidades", targetNamespace = "")
        boolean retornarPeriodicidades,
        @WebParam(name = "retornarBasesGeograficas", targetNamespace = "")
        boolean retornarBasesGeograficas,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param codigoOrgao
     * @param credencial
     * @param exercicio
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoOrgaosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterUnidadesOrcamentariasOrgao", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterUnidadesOrcamentariasOrgao")
    @ResponseWrapper(localName = "obterUnidadesOrcamentariasOrgaoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterUnidadesOrcamentariasOrgaoResponse")
    public RetornoOrgaosDTO obterUnidadesOrcamentariasOrgao(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoOrgao", targetNamespace = "")
        String codigoOrgao);

}
