
package br.gov.planejamento.sof.siop.servicoweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSQualitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", wsdlLocation = "file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSQualitativo.wsdl")
public class WSQualitativo_Service
    extends Service
{

    private final static URL WSQUALITATIVO_WSDL_LOCATION;
    private final static WebServiceException WSQUALITATIVO_EXCEPTION;
    private final static QName WSQUALITATIVO_QNAME = new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQualitativo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSQualitativo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSQUALITATIVO_WSDL_LOCATION = url;
        WSQUALITATIVO_EXCEPTION = e;
    }

    public WSQualitativo_Service() {
        super(__getWsdlLocation(), WSQUALITATIVO_QNAME);
    }

    public WSQualitativo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSQUALITATIVO_QNAME, features);
    }

    public WSQualitativo_Service(URL wsdlLocation) {
        super(wsdlLocation, WSQUALITATIVO_QNAME);
    }

    public WSQualitativo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSQUALITATIVO_QNAME, features);
    }

    public WSQualitativo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSQualitativo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSQualitativo
     */
    @WebEndpoint(name = "WSQualitativoPort")
    public WSQualitativo getWSQualitativoPort() {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQualitativoPort"), WSQualitativo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSQualitativo
     */
    @WebEndpoint(name = "WSQualitativoPort")
    public WSQualitativo getWSQualitativoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQualitativoPort"), WSQualitativo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSQUALITATIVO_EXCEPTION!= null) {
            throw WSQUALITATIVO_EXCEPTION;
        }
        return WSQUALITATIVO_WSDL_LOCATION;
    }

}
