
package br.gov.planejamento.sof.siop.servicoweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSQuantitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSQuantitativo {


    /**
     * 
     * @param credencial
     * @param acompanhamentoAcao
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcompanhamentoOrcamentarioDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarAcompanhamentoOrcamentario", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.CadastrarAcompanhamentoOrcamentario")
    @ResponseWrapper(localName = "cadastrarAcompanhamentoOrcamentarioResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.CadastrarAcompanhamentoOrcamentarioResponse")
    public RetornoAcompanhamentoOrcamentarioDTO cadastrarAcompanhamentoOrcamentario(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "acompanhamentoAcao", targetNamespace = "")
        AcompanhamentoOrcamentarioAcaoDTO acompanhamentoAcao);

    /**
     * 
     * @param credencial
     * @param proposta
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoPropostasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarProposta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.CadastrarProposta")
    @ResponseWrapper(localName = "cadastrarPropostaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.CadastrarPropostaResponse")
    public RetornoPropostasDTO cadastrarProposta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "proposta", targetNamespace = "")
        PropostaDTO proposta);

    /**
     * 
     * @param momentoId
     * @param tipoCaptacao
     * @param credencial
     * @param periodo
     * @param paginacao
     * @param exercicio
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcompanhamentoFisicoFinanceiroDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAcompanhamentoFisicoFinanceiro", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarAcompanhamentoFisicoFinanceiro")
    @ResponseWrapper(localName = "consultarAcompanhamentoFisicoFinanceiroResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarAcompanhamentoFisicoFinanceiroResponse")
    public RetornoAcompanhamentoFisicoFinanceiroDTO consultarAcompanhamentoFisicoFinanceiro(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "periodo", targetNamespace = "")
        Integer periodo,
        @WebParam(name = "momentoId", targetNamespace = "")
        Integer momentoId,
        @WebParam(name = "tipoCaptacao", targetNamespace = "")
        String tipoCaptacao,
        @WebParam(name = "paginacao", targetNamespace = "")
        PaginacaoDTO paginacao);

    /**
     * 
     * @param filtro
     * @param credencial
     * @param dataHoraReferencia
     * @param periodoOrdem
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcompanhamentoOrcamentarioDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAcompanhamentoOrcamentario", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarAcompanhamentoOrcamentario")
    @ResponseWrapper(localName = "consultarAcompanhamentoOrcamentarioResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarAcompanhamentoOrcamentarioResponse")
    public RetornoAcompanhamentoOrcamentarioDTO consultarAcompanhamentoOrcamentario(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "periodoOrdem", targetNamespace = "")
        Integer periodoOrdem,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroFuncionalProgramaticaDTO filtro,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

    /**
     * 
     * @param credencial
     * @param localizador
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoFinanceiroEmendasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEmendasLocalizador", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarEmendasLocalizador")
    @ResponseWrapper(localName = "consultarEmendasLocalizadorResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarEmendasLocalizadorResponse")
    public RetornoFinanceiroEmendasDTO consultarEmendasLocalizador(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "localizador", targetNamespace = "")
        LocalizadorDTO localizador);

    /**
     * 
     * @param filtro
     * @param credencial
     * @param paginacao
     * @param selecaoRetorno
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoExecucaoOrcamentariaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarExecucaoOrcamentaria", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentaria")
    @ResponseWrapper(localName = "consultarExecucaoOrcamentariaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentariaResponse")
    public RetornoExecucaoOrcamentariaDTO consultarExecucaoOrcamentaria(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroExecucaoOrcamentariaDTO filtro,
        @WebParam(name = "selecaoRetorno", targetNamespace = "")
        SelecaoRetornoExecucaoOrcamentariaDTO selecaoRetorno,
        @WebParam(name = "paginacao", targetNamespace = "")
        PaginacaoDTO paginacao);

    /**
     * 
     * @param credencial
     * @param paginacao
     * @param parametros
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoExecucaoOrcamentariaMensalDestDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarExecucaoOrcamentariaEstataisMensal", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentariaEstataisMensal")
    @ResponseWrapper(localName = "consultarExecucaoOrcamentariaEstataisMensalResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentariaEstataisMensalResponse")
    public RetornoExecucaoOrcamentariaMensalDestDTO consultarExecucaoOrcamentariaEstataisMensal(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "parametros", targetNamespace = "")
        ParametrosWebExecucaoOrcamentariaDTO parametros,
        @WebParam(name = "paginacao", targetNamespace = "")
        PaginacaoDTO paginacao);

    /**
     * 
     * @param filtro
     * @param credencial
     * @param paginacao
     * @param selecaoRetorno
     * @param mes
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoExecucaoOrcamentariaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarExecucaoOrcamentariaMensal", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentariaMensal")
    @ResponseWrapper(localName = "consultarExecucaoOrcamentariaMensalResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarExecucaoOrcamentariaMensalResponse")
    public RetornoExecucaoOrcamentariaDTO consultarExecucaoOrcamentariaMensal(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroExecucaoOrcamentariaDTO filtro,
        @WebParam(name = "selecaoRetorno", targetNamespace = "")
        SelecaoRetornoExecucaoOrcamentariaDTO selecaoRetorno,
        @WebParam(name = "mes", targetNamespace = "")
        Integer mes,
        @WebParam(name = "paginacao", targetNamespace = "")
        PaginacaoDTO paginacao);

    /**
     * 
     * @param filtro
     * @param credencial
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoNaturezasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarNaturezasDisponiveisParaProposta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarNaturezasDisponiveisParaProposta")
    @ResponseWrapper(localName = "consultarNaturezasDisponiveisParaPropostaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarNaturezasDisponiveisParaPropostaResponse")
    public RetornoNaturezasDTO consultarNaturezasDisponiveisParaProposta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroNaturezaDespesaDTO filtro);

    /**
     * 
     * @param credencial
     * @param proposta
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoPropostasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarProposta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarProposta")
    @ResponseWrapper(localName = "consultarPropostaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ConsultarPropostaResponse")
    public RetornoPropostasDTO consultarProposta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "proposta", targetNamespace = "")
        PropostaDTO proposta);

    /**
     * 
     * @param credencial
     * @param proposta
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoPropostasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "excluirProposta", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ExcluirProposta")
    @ResponseWrapper(localName = "excluirPropostaResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ExcluirPropostaResponse")
    public RetornoPropostasDTO excluirProposta(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "proposta", targetNamespace = "")
        PropostaDTO proposta);

    /**
     * 
     * @param credencial
     * @param periodo
     * @param exercicio
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoAcoesDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterAcoesDisponiveisAcompanhamentoOrcamentario", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesDisponiveisAcompanhamentoOrcamentario")
    @ResponseWrapper(localName = "obterAcoesDisponiveisAcompanhamentoOrcamentarioResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterAcoesDisponiveisAcompanhamentoOrcamentarioResponse")
    public RetornoAcoesDTO obterAcoesDisponiveisAcompanhamentoOrcamentario(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "periodo", targetNamespace = "")
        Integer periodo);

    /**
     * 
     * @param credencial
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoInformacaoCargaSiafiDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterDatasCargaSIAFI", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterDatasCargaSIAFI")
    @ResponseWrapper(localName = "obterDatasCargaSIAFIResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterDatasCargaSIAFIResponse")
    public RetornoInformacaoCargaSiafiDTO obterDatasCargaSIAFI(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial);

    /**
     * 
     * @param credencial
     * @param parametro
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoInformacaoCaptacaoPLOADTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterInformacaoCaptacaoPLOA", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterInformacaoCaptacaoPLOA")
    @ResponseWrapper(localName = "obterInformacaoCaptacaoPLOAResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterInformacaoCaptacaoPLOAResponse")
    public RetornoInformacaoCaptacaoPLOADTO obterInformacaoCaptacaoPLOA(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "parametro", targetNamespace = "")
        ParametroInformacaoCaptacaoPLOA parametro);

    /**
     * 
     * @param credencial
     * @param dataHoraReferencia
     * @param paginacao
     * @param exercicio
     * @param codigoMomento
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoPropostasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterProgramacaoCompletaQuantitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramacaoCompletaQuantitativo")
    @ResponseWrapper(localName = "obterProgramacaoCompletaQuantitativoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterProgramacaoCompletaQuantitativoResponse")
    public RetornoPropostasDTO obterProgramacaoCompletaQuantitativo(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "codigoMomento", targetNamespace = "")
        Integer codigoMomento,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia,
        @WebParam(name = "paginacao", targetNamespace = "")
        PaginacaoDTO paginacao);

    /**
     * 
     * @param retornarIdOcs
     * @param credencial
     * @param retornarIdUsos
     * @param dataHoraReferencia
     * @param retornarNaturezas
     * @param retornarRPs
     * @param exercicio
     * @param retornarFontes
     * @return
     *     returns br.gov.planejamento.sof.siop.servicoweb.RetornoApoioQuantitativoDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterTabelasApoioQuantitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterTabelasApoioQuantitativo")
    @ResponseWrapper(localName = "obterTabelasApoioQuantitativoResponse", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", className = "br.gov.planejamento.sof.siop.servicoweb.ObterTabelasApoioQuantitativoResponse")
    public RetornoApoioQuantitativoDTO obterTabelasApoioQuantitativo(
        @WebParam(name = "credencial", targetNamespace = "")
        CredencialDTO credencial,
        @WebParam(name = "exercicio", targetNamespace = "")
        Integer exercicio,
        @WebParam(name = "retornarNaturezas", targetNamespace = "")
        boolean retornarNaturezas,
        @WebParam(name = "retornarIdOcs", targetNamespace = "")
        boolean retornarIdOcs,
        @WebParam(name = "retornarIdUsos", targetNamespace = "")
        boolean retornarIdUsos,
        @WebParam(name = "retornarFontes", targetNamespace = "")
        boolean retornarFontes,
        @WebParam(name = "retornarRPs", targetNamespace = "")
        boolean retornarRPs,
        @WebParam(name = "dataHoraReferencia", targetNamespace = "")
        XMLGregorianCalendar dataHoraReferencia);

}
