
package br.gov.planejamento.sof.siop.servicoweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSQuantitativo", targetNamespace = "http://servicoweb.siop.sof.planejamento.gov.br/", wsdlLocation = "file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSQuantitativo.wsdl")
public class WSQuantitativo_Service
    extends Service
{

    private final static URL WSQUANTITATIVO_WSDL_LOCATION;
    private final static WebServiceException WSQUANTITATIVO_EXCEPTION;
    private final static QName WSQUANTITATIVO_QNAME = new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQuantitativo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/forpdi/repo/forpdi-java/src/main/resources/WSQuantitativo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSQUANTITATIVO_WSDL_LOCATION = url;
        WSQUANTITATIVO_EXCEPTION = e;
    }

    public WSQuantitativo_Service() {
        super(__getWsdlLocation(), WSQUANTITATIVO_QNAME);
    }

    public WSQuantitativo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSQUANTITATIVO_QNAME, features);
    }

    public WSQuantitativo_Service(URL wsdlLocation) {
        super(wsdlLocation, WSQUANTITATIVO_QNAME);
    }

    public WSQuantitativo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSQUANTITATIVO_QNAME, features);
    }

    public WSQuantitativo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSQuantitativo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSQuantitativo
     */
    @WebEndpoint(name = "WSQuantitativoPort")
    public WSQuantitativo getWSQuantitativoPort() {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQuantitativoPort"), WSQuantitativo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSQuantitativo
     */
    @WebEndpoint(name = "WSQuantitativoPort")
    public WSQuantitativo getWSQuantitativoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicoweb.siop.sof.planejamento.gov.br/", "WSQuantitativoPort"), WSQuantitativo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSQUANTITATIVO_EXCEPTION!= null) {
            throw WSQUANTITATIVO_EXCEPTION;
        }
        return WSQUANTITATIVO_WSDL_LOCATION;
    }

}
